scripts/bb-determine-layers

This allows for variable references amongst the layers, particularly from a layer to its dependencies.
JIRA: SB-19738
Based upon #5.

bb-determine-layers: use common data for all parsed layer.conf files

---

conf/local.conf.sample

This reduces the quite aggressive default from `1.5*NUM_CORES` and `2.0*NUM_CORES` to `NUM_CORES` for both variables, which is oe-core's default.

local.conf.sample: restore default jobs/threads

---

meta-sokol-flex-support/recipes-bsp/96boards-tools/96boards-tools_0.12.bb

This fixes the LIC_FILES_CHKSUM for 96boards-tools which points
to an invalid file and updates the md5sum accordingly.
JIRA: https://jira.alm.mentorg.com/browse/SB-19969
Signed-off-by: Awais Belal <awais_belal@mentor.com>

96boards-tools: fix LIC_FILES_CHKSUM

---

conf/local.conf.sample
meta-sokol-flex-common/classes/codebench-environment-setup-d-hack.bbclass
meta-sokol-flex-common/classes/sdk_codebench_metadata.bbclass
meta-sokol-flex-common/classes/sdk_extra_vars.bbclass
meta-sokol-flex-distro/conf/distro/sokol-flex.conf
meta-sokol-flex-support/recipes-core/meta/codebench-makefile.bb
meta-sokol-flex-support/recipes-core/meta/nativesdk-relocate-makefile.bb
scripts/setup-ubuntu

- Use SDK naming
- Align with Yocto SDK
- Pull SDK enhancements and CodeBench metadata generation from other layers
- More pleasant title, aligned with upstream: `ADE for ${SDKMACHINE}-${IMAGE_BASENAME}-${MACHINE}-${SDK_VERSION}` -> `${DISTRO_NAME} ${IMAGE_BASENAME} SDK for ${MACHINE}`
JIRA: MELMR-1143
This is based upon #2. Rebased version of https://github.com/MentorEmbedded/meta-mentor/pull/1485.

Migration from ADE to Yocto SDK

---

scripts/bb-determine-layers
scripts/setup-flex-builddir

This aligns with the behavior of bitbake itself and allows for us to use this mechanism to pull in additional layers whenever a vendor BSP layer is included, so we can apply necessary integration changes.
JIRA: MELMR-1099
Example usage in our bblayers.conf.sample:
```bitbake
LAYERRECOMMENDS_meta-polarfire-soc-yocto-bsp:append = " mentor-vendor-polarfire-soc"
```
Migrated from <https://github.com/MentorEmbedded/meta-mentor/pull/1487>

Allow bblayers.conf to affect our bb-determine-layers script

---

conf/local.conf.sample
meta-sokol-flex-distro/conf/distro/sokol-flex.conf
scripts/setup-flex-builddir

There's no need to hardcode this knowledge in the setup scripts when we can set it in the metadata instead.
This makes https://github.com/MentorEmbedded/meta-sokol-flex/pull/17 unnecessary.

Set TOOLCHAINS_PATH via the metadata

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf

packagegroup-core-weston makes more sense as the feature package for graphics
when using wayland. It provides the packages that we were using plus some
additional tools which would be helpful. This also allows us to align for this
component with vendor configurations.
JIRA: https://jira.alm.mentorg.com/browse/SB-19826
Signed-off-by: Awais Belal <awais_belal@mentor.com>

[kirkstone] sokol-flex: use the core packagegroup for weston feature packages

---

meta-sokol-flex-common/classes/sdk_codebench_metadata.bbclass

These are needed by CodeBench.

sdk_codebench_metadata.bbclass: add TOOLCHAIN_PATH and TOOLCHAIN_GDB_PATH

---

meta-sokol-flex-staging/recipes-core/udev/udev-extraconf_%.bbappend

This adds fix for systemd automount which has been fixed differently in
upstream oe-core layer.
Ref: https://github.com/openembedded/openembedded-core/commit/a3c93ec301a34413f91e3edb70c16454ebcdcdf2
With systemd-udev.service, the kernel and control sockets for systemd-udev
fails and hence systemd-udevd service fails to start which hangs the boot if
weston is enabled. This issue has been addressed upsrtream and fix is being included
here.
TODO: All the changes in flex-staging layer for udev-extraconf has been merged
upstream but will be part of 4.0.3 release which is planned to be out in Sep 2022.
For the time being, we are including the fix here but all these staging layer
changes should be dropped from here once 4.0.3 is out and we shift to that release.
JIRA-ID: SB-19773
Signed-off-by: …

staging/udev-extraconf: include fix for systemd automount issue from upstream

---

meta-sokol-flex-staging/recipes-bsp/96boards-tools/96boards-tools/0001-resize-helper-make-parted-not-prompt-for-user-interv.patch

Our earlier attempt failed due to a negligence of testing the fix with script
mode at runtime with a fresh install i.e. the change was run on an already
resized root so the issue did not show up.
This really fixes the issue by leveraging an internal option (pretend-tty-input)
of parted with the older approach of echoing and piping the confirmation to the
command.
JIRA: https://jira.alm.mentorg.com/browse/SB-19819
Signed-off-by: Awais Belal <awais_belal@mentor.com>

staging:96boards-tools: really fix resizing on the first boot

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf

This was moved to meta-flex-ref-bsps where it belongs. It also hasn't been updated for linux-flex.

sokol-flex: remove BB_GIT_SHALLOW_REVS for linux-mel

---

meta-sokol-flex-support/recipes-core/meta/archive-release.bb

This will be useful as a sanity check to watch for unexpected large non-shallow git tarballs.
With this you'll get warnings such as this if a download is larger than expected:
```
WARNING: archive-release-1.0-r0 do_archive_downloads: Download gitshallow_git.yoctoproject.org.linux-yocto.git_3f298fc-1_v5.15.standard.qemuarm64.tar.gz size (213.5MiB) exceeds configured threshold of 200.0MiB for gitshallow*
```
The default configuration only warns for gitshallow > 220MiB or other downloads > 300MiB.
Based on https://github.com/MentorEmbedded/meta-sokol-flex/pull/22 to avoid conflicts.

archive-release: implement download size sanity checks

---

conf/local.conf.sample
meta-sokol-flex-distro/classes/mem-per-cpu-scaling.bbclass
meta-sokol-flex-distro/conf/distro/sokol-flex.conf

A new class is added warns if memory-per-cpu-core is low, and set
BB_NUMBER_THREADS_SCALED and PARALLEL_MAKE_SCALED with scaled down
values.
Class behavior is configured using the MEM_PER_CPU_SCALING_THRESHOLDS
variable. By default, if we have less than 4gb per CPU core, we warn and
reduce the make jobs to cpus/2. If we have less than 2gb per CPU core,
we warn and reduce both bitbake threads and make jobs to cpus/2.
An example of how to set the variables to the scaled values is provided in
local.conf.sample.
JIRA: SB-20030

Implement jobs/threads scaling support

---

meta-sokol-flex-distro/recipes-multimedia/pulseaudio/pulseaudio_%.bbappend

This is a small change to include pusleaudio module `module-switch-on-connect` in the release.
It was noticed while testing the audio playback through g-streamer that it will be more user friendly if we add this module. This module automatically changes the sink when a new audio device is connected to host machine.

pulseaudio: make module-switch-on-connect available

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf

Replace `+snapshot-${DATE}` in `DISTRO_VERSION` with `-alpha`, and replace `-alpha` in `SDK_VERSION` with the timestamp in seconds as a suffix.
JIRA: SB-20310, SB-20454
Previous values:
```bitbake
DISTRO_VERSION="13.0+snapshot-20220913"
SDK_VERSION="13.0-snapshot"
```
New values:
```bitbake
DISTRO_VERSION="13.0-alpha"
SDK_VERSION="13.0.202209161514"
```

sokol-flex: correct pre-release versions

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf

In https://github.com/MentorEmbedded/meta-sokol-flex/pull/52/ ending of section and starting of next were accidentally removed. This commit fixes the section starting and ending.
Signed-off-by: Muhammad Hamza <muhammad_hamza@mentor.com>

sokol-flex.conf: Fix section starting and ending

---

conf/local.conf.sample
meta-sokol-flex-distro/conf/distro/sokol-flex.conf
meta-sokol-flex-support/recipes-core/images/flex-image.inc

This PR adds 'tools-sdk' to 'IMAGE_FEATURES_DEVELOPMENT', so that we get support for on-target development.
While at it, also add hwcodecs image feature when alsa is in COMBINED_FEATURES, and remove FEATURE_PACKAGES_hwcodecs from x11 FEATURE_PACKAGES

Support on-target development for development-image, and other fixes

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf
scripts/setup-rh

SB-20046: The Flex OS should build on RHEL 9.
I had to re-create this PR. The old one got messed up.
@Noor-Ahsan this is the one which was already approved. Please merge it.
Previous PR URL is https://github.com/MentorEmbedded/meta-sokol-flex/pull/57/

Add support for RHEL9.

---

meta-sokol-flex-distro/conf/distro/include/vendor.inc
meta-sokol-flex-distro/conf/distro/sokol-flex.conf

Determine the default vendor config filename based upon the layer name
of the layer which provides the MACHINE .conf, with meta- removed. For
example, for icicle-kit-es, `conf/vendor/polarfire-soc-yocto-bsp.conf`
would be included by default. Either VENDOR or VENDOR_CONF may be
overridden by a MACHINE, as will be the case for our official Sokol Flex
BSP machines.

sokol-flex: default VENDOR based on MACHINE layer name

---

meta-sokol-flex-staging/dynamic-layers/virtualization-layer/recipes-containers/docker/docker%.bbappend
meta-sokol-flex-staging/dynamic-layers/virtualization-layer/recipes-containers/docker/files/0001-libnetwork-use-GO-instead-of-go.patch

This fixes builds with riscv64 by obeying `GO_LINKSHARED` from the go bbclasses.
JIRA: SB-20713
Signed-off-by: Christopher Larson <chris_larson@mentor.com>

docker-moby: backport 2d0f725 from newer meta-virtualization

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf

We need to remove Ubuntu 20.04 from SANITY_TESTED_DISTROS because it is no longer a supported version as flex build host.
JIRA: SB-20045.
Signed-off-by: Akif akif_tariq@mentor.com

sokol-flex.conf: Remove old version of Ubuntu

---

meta-sokol-flex-staging/classes/toolchain-scripts-mingw32.bbclass

Modify toolchain-scripts-mingw32.bbclass to add a check in environment-setup script which removes trailing slash in path of SDKROOT.
This is needed to avoid multiple adjacent slashes in paths which are produced by appending to SDKROOT.
JIRA-ID: SB-20623
Signed-off-by: Muhammad Hamza <muhammad_hamza@mentor.com>

toolchain-scripts-mingw32.bbclass: Remove trailing slash in path

---

meta-sokol-flex-common/classes/image-root-password.bbclass

The reason for this is that in Yocto Honister shadow version was updated, and shadow custom support in OE core for cleartext passwords was removed. For more details see:
https://docs.yoctoproject.org/migration-guides/migration-3.4.html#miscellaneous and
https://docs.yoctoproject.org/ref-manual/variables.html#term-EXTRA_USERS_PARAMS
JIRA-ID: SB-20424
Signed-off-by: Ahsan Hussain <ahsan_hussain@mentor.com>

image-root-password: use encrypted password

---

meta-sokol-flex-support/recipes-core/meta/archive-release.bb

Rather than placing these arguments within the file we pass to --files-from, just pass those arguments directly. This avoids build failures with recent tar, as is used in Ubuntu 22.04.
JIRA: SB-20872

archive-release: avoid using --transform in tar --files-from

---

meta-sokol-flex-common/classes/image-root-password.bbclass

The root user login on development-image and production-image does not work when ROOT_PASSWORD is not set i.e. by default. This is due to a bug in the image-root-password.bbclass function encrypt_root_pw that does an invalid comparison of the password string with 'None'. It should rather compare it with an empty string as that is the default state of the ROOT_PASSWORD var.
Otherwise, the ACTUAL_ROOT_PASSWORD evaluates to "'*0'" which is not a proper encrypted password.
JIRA: SB-20967
Signed-off-by: Arsalan H. Awan <Arsalan_Awan@mentor.com>

image-root-password.bbclass: fix default empty root password login

---

scripts/release/flex-checkout

By prematurely setting our branch, the later logic to check out that
branch does nothing, as we're already on it. The problem is we never
actually did a checkout, so no files exist. Explicitly specify a default
branch which does not match our own to avoid skipping the later
checkout.
JIRA: SB-21205
Signed-off-by: Christopher Larson <chris_larson@mentor.com>

flex-checkout: default the git init branch to main, not $branch

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf
meta-sokol-flex-distro/dynamic-layers/virtualization-layer/conf/local.conf.append

IMAGE_FEATURES in local.conf.append files are removed to distro configuration to separate
them from USER_FEATURES
local.conf.append: removal of EXTRA_IMAGE_FEATURES from feature layer
sokol-flex.conf: Addition of EXTRA_IMAGE_FEATURES to distro layer, inclusion of distro configuration path for iot feature
JIRA: SB-20851
Signed-off-by: Aoun Ahmed <aoun_ahmad@mentor.com>

sokol-flex-distro: improve layer by separating user and image features 

---

scripts/release/flex-checkout

Due to the use of '-' as the separator in our manifest filenames, we
have to know precisely how to get the machine name back out of it, which
means the number of dashes in the DISTRO is a factor. Now that we're
`sokol-flex` rather than `mel`, we need to adjust the cut to the 4th,
not 3rd dash, and also strip off the +snapshot- suffix.
JIRA: SB-21211
Signed-off-by: Christopher Larson <chris_larson@mentor.com>

flex-checkout: fix for 'sokol-flex' and +snapshot

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf

0.0 will still be appended for bsp and patch versions, resulting in a final complete version string of 13.0.0 as expected. SDKs have their timestamps appended separately, so that isn't affected by this.
JIRA: SB-21242
Signed-off-by: Christopher Larson <chris_larson@mentor.com>

sokol-flex: change version from 13.0+snapshot-${DATE} to 13

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf
meta-sokol-flex-staging/files/toolchain-shar-extract.sh

Specifically, this shows the value of the `SDK_VERSION` variable.
JIRA: SB-20916
For example:
```
$ ./tmp/deploy/sdk/sdk-x86_64-sokol-flex-13.0.202212272016-development-image-icicle-kit-es-flex.sh -v
13.0.202212272016
```

toolchain-shar-extract.sh: add -v argument to show sdk version

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf
scripts/capdebuginfo

For re-branding requirements we need to remove all the possible occurrences of string mel or mentor with flex. Most of such files have been renamed, and occurrences of such strings.
JIRA ID: SB-21223
Signed-off-by: Akif Tariq <akif.tariq@siemens.com>

rebranding: removed mel occurences with flex

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf

Add Sokol Omni as a tested distro as it will be used in WSL2
JIRA: SB-21031
Signed-off-by: Arslan Ahmad <arslan_ahmad@mentor.com>

sokol-flex: Add Sokol Omni as supported distro

---

meta-sokol-flex-support/recipes-core/meta/archive-release.bb
scripts/release/flex-checkout

Rather than flex-checkout extracting the machine from the manifest filename,
it's better to store and read it in a way it can use directly.
JIRA: SB-21264

Determine the default machine from a file rather than a file name

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf

Relocate $APPEND and related variables to flex-bsp-common so that
all boot related params for uboot and grub are unified and edited
at one place.
sokol-flex-conf: removal of $APPEND and related variables so we can
shift it to flex-bsp-common.inc.
JIRA ID: SB-20844
Signed-off-by: Aoun Ahmed <aoun.ahmad.ext@siemens.com>

sokol-flex-distro: relocate APPEND to flex-bsp-common

---

conf/local.conf.sample
meta-sokol-flex-distro/conf/distro/sokol-flex.conf

flex-bsp has moved to machine overrides. Update all instances accordingly
JIRA: SB-21746

distro: update flex-bsp overrides

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf
meta-sokol-flex-support/recipes-core/meta/archive-release.bb

This should start at 0 as the other version components do, for consistency.
JIRA: SB-21762

sokol-flex, archive-release: reset SCRIPTS_VERSION to 0

---

scripts/setup-flex-builddir
setup-environment

This script iterates through the arguments solely to get the correct `$BUILDDIR`, but doesn't have full fledged option parsing since it's actually a light wrapper around setup-flex-builddir.  During this iteration, it seems '$10' gets expanded as '$1' followed by a 0, which isn't what we're looking for here, so use '${}' syntax instead.
JIRA: SB-21796

setup-environment: fix argument handling for args >9

---

scripts/setup-debian
scripts/setup-rh
scripts/setup-ubuntu

The recipetool utility requires the python's setuptools package. The setup scripts have been updated to install the python's setuptools package.
JIRA: SB-21904

setup scripts: install python3 setuptools package

---

meta-sokol-flex-distro/dynamic-layers/openembedded-layer/recipes-support/lvm2/lvm2_%.bbappend

Use require instead of include to make sure we get the required .inc file when needed.
JIRA: SB-21389

distro:lvm2: use require for .inc file

---

conf/conf-notes.txt

Changes this:
```
Determining layers to include for MACHINE 'icicle-kit-es-flex'...core,flex-bsp-common,flex-bsp-polarfire-icicle-kit,flex-polarfire-common,flex-swupdate,flex-user-examples,meta-polarfire-soc-yocto-bsp,openembedded-layer,riscv-layer,sokol-flex-common,sokol-flex-distro,sokol-flex-support,swupdate
Checking for optional layers...
Common targets are:
development-image
production-image
production-image requires that the ROOT_PASSWORD variable be set. See
conf/local.conf for details.
For qemu machines, you can also run the generated qemu images with a command
like 'runqemu qemux86'.
```
To this:
```
Determining layers to include for MACHINE 'icicle-kit-es-flex'...core,flex-bsp-common,flex-bsp-polarfire-icicle-kit,flex-polarfire-common,flex-swupdate,flex-user-examples,meta-polarfi …
```

conf-notes.txt: remove qemu lines and format

---

meta-sokol-flex-staging/files/relocate_sdk.sh

Also ensure we only select one.
Without this change, it may select the .debug version of ld-linux in
SDKs which include debug info, which is usual.
JIRA: SB-22047

relocate_sdk.sh: find ld-linux only at toplevel

---

scripts/setup-rh

The setuptools package is required by recipetool utility.
Explicitly installing the setuptool package in setup-rh
script to fulfil the dependency.
JIRA: SB-22045
Signed-off-by: Arsalan Saleem <arsalan_saleem@mentor.com>

setup scripts: install python3-setuptools package. 

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf

Support for encrypted-fs has been implemented for imx in meta-flex-ref-bsps repository. This change enables the encrypted-fs feature when it is enabled in main
local.conf
JIRA-ID: SB-21384

sokol-flex.conf: add feature support for encrypted-fs

---

meta-sokol-flex-distro/recipes-support/curl/curl_%.bbappend

we need to remove ssl from PACKAGECONFIG to avoid the invalid-packageconfig warning. ssl has been deprecated upstream.
Reference: https://github.com/openembedded/openembedded-core/commit/eef6c45fc6ec0a496791123e8ba2f400a5d9d468
JIRA-ID: SB-21051

curl: remove ssl from packageconfig

---

meta-sokol-flex-distro/recipes-core/psplash/psplash_git.bbappend

By default startup message is enabled. This draws a stripe close to the bottom of the screen with the background color specified(currently black).
This might not be visible in some cases, where the image is centered and the remaining area is filled with the background color.
Disable startup message to avoid the black rectangle displayed over the psplash image.

psplash: disable startup message

---

scripts/build-setup-environment.in

With the recent bitbake update, it is utilizing locale.getlocale() and locale.setlocale() from the python locales module. This module has a limitation when the host doesn't have the encoding defined, so e.g. if we have:
```
$ locale
...
LC_CTYPE="en_IN"
...
```
it will not pick the correct encoding:
```
$ python3
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale()
('en_IN', 'ISO8859-1')
```
and it will fail:
```
>>> default_locale = locale.getlocale(locale.LC_CTYPE)
>>> print(default_locale)
('en_IN', 'ISO8859-1')
>>> locale.setlocale(locale.LC_CTYPE, default_locale)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File …
```

scripts:setup-env: set LC_CTYPE for bitbake

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf

This ensures that these values in the environment-setup files differ
between the base and multilib configurations.
JIRA: SB-22377

sokol-flex: add multilib prefix to SDK title and identifier

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf

There was a typo: getvar instead of getVar, which causes the do_populate_sdk
task to fail when these variables are used in our postprocessing functions.
JIRA: SB-22499

sokol-flex: fix getvar call which broke sdk builds

---

scripts/release/flex-checkout

This occurs if the manifest prompt is interrupted (ex. ^C). By checking
to see if the file exists and is non-empty when determining whether to
prompt, we can avoid this error:
sed: can't read .info: No such file or directory
JIRA: SB-22545

flex-checkout: re-prompt if .manifest is a zero-byte file

---

meta-sokol-flex-staging/classes/populate_sdk_qt6_base.bbclass
meta-sokol-flex-staging/dynamic-layers/qt6-layer/recipes-qt/qt6/qtbase_%.bbappend

Cherry-pick [5cbac6cf356b94db8dbadbc7b3b9149b6374ef72](https://code.qt.io/cgit/yocto/meta-qt6.git/commit/?h=5cbac6cf356b94db8dbadbc7b3b9149b6374ef72) from meta-qt6 to
fix populate_sdk failure due to libdir mismatch between nativesdk and
target.
JIRA: SB-22426

qt6: sdk: rewrite cmake toolchain file without environment variables

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf
meta-sokol-flex-staging/recipes-core/glibc/ldso-config.bb

A new recipe installs extra ld.so configuration files for multilib
library paths, to ensure the dynamic linker and ldconfig can find all
the installed libraries.
This gives us correct ldconfig behavior, where `ldconfig -p` lists the
libraries from all multilib library paths.
Before:
```
root@qemuarm64:~# ldconfig -p|grep liblttng-ust-dl
liblttng-ust-dl.so.1 (libc6,hard-float) => /usr/lib/liblttng-ust-dl.so.1
```
After:
```
root@qemuarm64:~# ldconfig -p|grep liblttng-ust-dl
liblttng-ust-dl.so.1 (libc6,AArch64) => /usr/lib64/liblttng-ust-dl.so.1
liblttng-ust-dl.so.1 (libc6,hard-float) => /usr/lib/liblttng-ust-dl.so.1
```
JIRA: SB-25565

Include multilib library paths in ld.so configuration

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf

This is expected to already be installed by Sourcery Analyzer.
JIRA: SB-22571

sokol-flex: add libxcrypt to the multilib runtime packages

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf
meta-sokol-flex-staging/recipes-kernel/lttng/lttng-tools_%.bbappend

- lttng-tools: configure paths to 64 and 32 bit consumerd
- sokol-flex: include multilib versions of lttng-tools
JIRA: SB-22623, SB-22565

Multilib fixes for lttng-tools

---

meta-sokol-flex-common/classes/rootfs-disable-tty1-login.bbclass
meta-sokol-flex-support/recipes-core/images/flex-image.inc

BSPs that want it disabled may add disable-tty1-login to their
MACHINE_FEATURES, which will result in its addition to IMAGE_FEATURES
for flex images, which will disable the login.
JIRA: SB-22595

Disable tty1 login for BSPs that choose to do so

---

meta-sokol-flex-staging/recipes-kernel/lttng/lttng-ust_2.13.6.bb

This is necessary to fix a tracing issue where source lookup is disabled
because the"ip" context information is missing.
JIRA: SA-5426

lttng-ust: upgrade from 2.13.5 to 2.13.6

---

meta-sokol-flex-distro/recipes-graphics/wayland/weston-init.bbappend
meta-sokol-flex-distro/recipes-graphics/wayland/weston-init/weston-init.sh

Set WAYLAND_DISPLAY by default for console or ssh users so they are able
to run wayland programs more easily. This fixes the ability to run
programs over ssh for Qt Creator, for example.
JIRA: SB-22247

weston-init: set WAYLAND_DISPLAY in the default shell profile

---

meta-sokol-flex-distro/conf/distro/sokol-flex.conf
meta-sokol-flex-staging/recipes-kernel/lttng/lttng-tools/0001-Ensure-that-the-consumerd-configure-arguments-are-us.patch
meta-sokol-flex-staging/recipes-kernel/lttng/lttng-tools_%.bbappend

* Patch lttng-tools to obey its configure arguments for consumerd paths for multilibs
* Adjust lttng-tools packaging to avoid 32-bit binaries overwriting 64-bit ones

Fix lttng-tools multilib issues

---

meta-sokol-flex-staging/recipes-connectivity/openssl/openssl_%.bbappend

Ignore the do_package_qa_multilib check to suppress this warning:
WARNING: lib32-openssl-3.0.9-r0 do_package: QA Issue: lib32-openssl package lib32-openssl - suspicious values 'cryptodev-module' in RRECOMMENDS [multilib]
The do_package_qa_multilib PACKAGE FUNC does not obey INSANE_SKIP so we modify it directly. In the long term, we should also consider fixing the upstream class to obey INSANE_SKIP properly.
JIRA: SB-22762

openssl: quiet multilib QA warning about suspicious value

---

meta-sokol-flex-staging/recipes-kernel/lttng/lttng-tools/0001-Ensure-that-the-consumerd-configure-arguments-are-us.patch
meta-sokol-flex-staging/recipes-kernel/lttng/lttng-tools_%.bbappend

As was diagnosed by @aarslan7  (great work, Arslan!), the configure script was
unconditionally defining the variables for consumerd, but this resulted in a
value of the empty string, not NULL, and the code only checked for non-NULL.
Change the code to actually check if the binary exists with stat before running
it. This is consistent with other uses of these variables in the code, ensures
it isn't used as the empty string, and ensures that it doesn't try to run a
missing binary in general.
JIRA: SB-22858

lttng-tools: fix non-multilib failure
